### PR TITLE
chore: Update multiple dependencies

### PR DESCRIPTION
**Pull request by silathdiir**
### Summary

1. Update according to [dependabot](https://github.com/apps/dependabot) PRs.
#133
#134
#135
#136
2. Test with `make import_mock_data` on local.

### CODE REVIEW

**Comment by OrestTa** [comment]
thx! Smoke testing still needed or done already?

**Comment by silathdiir** [comment]
> thx! Smoke testing still needed or done already?

Yes, already tested. I tested this update with `make import_mock_data` on local.

**Review by OrestTa — DISMISSED** [review]
GOtcha, thx; lgtm otherwise

**Comment by silathdiir** [comment]
Integrate and test (on local) with `rust_decimal` and `serde_json` upgrades.

**Review by OrestTa — APPROVED** [review]

**Review by 0xmountaintop — APPROVED** [review]

**Pull request merged**
